### ISSUE TITLE
升级到 taro-3.3.6 之后，全局css样式不生效

### ISSUE THREAD

**Issue by transtone** [pcdotfan/taro-plugin-tailwind#55]
这些样式虽然可以在 virtual:windi.css 文件中找到，但是并不会对页面元素生效。

```css
/* windicss layer base */
*, ::before, ::after {
  box-sizing: border-box;
  border-width: 0;
  border-style: solid;
  border-color: #e5e7eb;
}

* {
  --tw-ring-inset: var(--tw-empty, /*!*/ /*!*/);
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
}
```

之前用 taro-3.2.x 版本的时候是正常的。
